config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}

  root to: 'dashboards#index'

  resources :users do
    resources :exercises
  end

  resources :dashboards, only: [:index] do
    collection do
      post :search, to: 'dashboards#search'
    end
  end

  resources :friendships, only:[:show, :create, :destroy]
  resources :messages, only: [:create]

  mount ActionCable.server => "/cable"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user

  alias_attribute :workout_details, :workout
  alias_attribute :activity_date, :workout_date

  validates :duration, presence: true
  validates :duration, numericality: {greater_than: 0}
  validates :workout_details, presence: true
  validates :activity_date, presence:true

  # default_scope {where('workout_date > ?', 7.days.ago)
  #                 .order(workout_date: :desc)}
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :exercises, dependent: :destroy
  has_many :friendships
  has_many :friends, through: :friendships, class_name: "User"
  has_one :room
  has_many :messages

  validates :email, :first_name, :last_name, :password, presence:true

  after_create :create_chatroom


  self.per_page = 10

  def self.search_by_name(term)
    names_array = term.split(' ')
    if names_array.length == 1
      where('lower(first_name) LIKE ? OR lower(last_name) LIKE ?', "%#{names_array[0].downcase}%","%#{names_array[0].downcase}%").order(:first_name)
    else
      where('lower(first_name) LIKE ? OR lower(last_name) LIKE ? OR lower(first_name) LIKE ? OR lower(last_name) LIKE ?', "%#{names_array[0].downcase}%","%#{names_array[0].downcase}%","%#{names_array[1].downcase}%","%#{names_array[1].downcase}%").order(:first_name)
    end
  end

  def follows_or_same?(athelete)
    if self == athelete || friendships.map(&:friend).include?(athelete)
      return true
    else
      return false
    end
  end

  def full_name
    [first_name, last_name].join(" ")
  end

  def current_friendship(friend)
    friendships.where(friend: friend).first
  end

  private

  def create_chatroom
    hyphenated_user_name = self.full_name.split(' ').join('-')
    Room.create(name: hyphenated_user_name, user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_room
    @room ||= Room.find(session[:current_room]) if session[:current_room]
  end

  helper_method :current_room



end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @atheletes = User.paginate(:page => params[:page])
  end
  def search
    @search_term =  params[:search_name]
    @atheletes = User.search_by_name(@search_term)
      .paginate(:page => params[:page])
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only:[:show,:edit,:update,:destroy]
  def index
    set_current_room
    @exercises = current_user.exercises.where('workout_date > ?', 7.days.ago).order(workout_date: :desc)
    @friends = current_user.friends
    @message = Message.new
    @messages = current_room.messages if current_room
    @followers = Friendship.where( friend_id: current_user.id )

  end

  def show
  end

  def new
    @exercise = current_user.exercises.new
  end
  def create
    @exercise = current_user.exercises.new(exercise_params)
    if @exercise.save
      flash[:notice] = 'Exercise has been created'
      redirect_to user_exercise_path(current_user, @exercise)
    else
      flash.now[:danger] = 'Exercise could not be created'
      render :new

    end


  end

  def edit

  end

  def update

    if @exercise.update(exercise_params)
      flash[:success] = 'Exercise has been updated'
      redirect_to user_exercise_path(current_user, @exercise)
    else
      flash.now[:danger] = 'Exercise could not be updated'
      render :edit
    end
  end
  def destroy

    if @exercise.delete
      flash[:success] = 'Exercise has been deleted'
    else
      flash[:danger] = 'Exercise could not be deleted'
    end
      redirect_to user_exercises_path(current_user)
  end

  private

  def set_exercise
    @exercise = Exercise.find(params[:id])
  end
  def exercise_params
    params.require(:exercise).permit(:duration, :workout, :workout_date)
  end
  def set_current_room
    if params[:roomId]
      @room = Room.find_by(id: params[:roomId])
    else
      @room = current_user.room
    end
    session[:current_room] = @room.id if @room.id
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def show
    @friend = Friendship.find(params[:id]).friend
    @exercises = @friend.exercises.where('workout_date > ?', 7.days.ago).order(workout_date: :desc)
  end

  def create
    friend = User.find(params[:friend_id])
    params[:user_id] = current_user.id

    Friendship.create(friendship_params) unless current_user.follows_or_same?(friend)
    redirect_to root_path
  end

  def destroy
    friendship = Friendship.find(params[:id])
    if friendship.destroy
      flash[:success] = "#{friendship.friend.full_name} was unfollowed"
    else
      flash.now[:danger] = 'Friendship was not deleted'
    end
    redirect_to user_exercises_path(current_user)
  end

  private

  def friendship_params
    params.permit(:friend_id, :user_id)
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @message = current_user.messages.build(message_params)
    @message.room = current_room

    @message.save
    redirect_to user_exercises_path(current_user)
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/dashboards/index.html.erb
<div class="jumbotron">
  <h1>Workout Lounge!</h1>
  <p>Show off your workout</p>
</div>
<div class="row">
  <div class="col-md-12 text-center">
    <h2>List of Members</h2>
    <%= will_paginate @atheletes, render: BootstrapPagination::Rails, class: "pull-left paginate" %>
  </div>
</div>
<div class="row">
  <% @atheletes.each do |athelete|%>
    <div class="col-md-10 col-md-offset-1 well member">
      <%= athelete.full_name %>
      <%if current_user%>
      <%= link_to "Follow", friendships_path(friend_id: athelete.id), method: :post, class:'btn btn-success pull-right' unless current_user.follows_or_same?(athelete) %>
      <% end %>
    </div>
  <% end %>

</div>

app/views/dashboards/search.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h2>Search Results for <%= @search_term %></h2>
    <%= will_paginate @atheletes, render: BootstrapPagination::Rails, class: "pull-left paginate" %>
  </div>
</div>
<div class="row">
  <% @atheletes.each do |athelete|%>
    <div class="col-md-10 col-md-offset-1 well member">
      <%= athelete.full_name %>
    </div>
  <% end %>

</div>

app/views/exercises/_form.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= form_for([current_user, @exercise], html: {class:'form-horizontal', role:"form"}) do |f| %>
      <% if @exercise.errors.any? %>
        <div class="panel panel-danger">
          <div class="panel-heading">
            <strong class='panel-title'>The form has <%= pluralize(@exercise.errors.count, "error")%></strong>
          </div>
          <div class="panel-body">
            <ul>
              <% @exercise.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :duration, "Duration (min)" %>
        </div>
        <div class="col-md-8">
          <%= f.number_field :duration, class: "form-control", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :workout, "Workout Details" %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :workout, class: "form-control", rows: 10, placeholder:"eg. Jogging"%>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :workout_date, "Activity Date" %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :workout_date, class: "form-control",size:30,id:'exercise_workout_date'%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-8 col-md-offset-2">
          <%= f.submit class:"btn btn-success btn-lg pull-left"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/exercises/edit.html.erb
<h2 class="text-center">Edit Workout for <%= current_user.full_name%></h2>
<%= render 'form'%>
<div class="col-md-12">
  <%= link_to 'Back', user_exercises_path(current_user), class: "btn btn-primary link", id:'new-exer-btn'%>
</div>

app/views/exercises/index.html.erb
<% content_for(:whole_page) do %>
  <h2 class="text-center">My Workouts (past 7 days)</h2>
  <div class="col-md-7 col-xs-12">
    <% unless @exercises.empty? %>
    <table class="table tabel-striped">
      <thead>
        <tr>
          <th>Duration (min)</th>
          <th>Workout Details</th>
          <th>Activity Date</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @exercises.each do |exercise| %>
        <tr>
          <td><%= exercise.duration %></td>
          <td><%= truncate(exercise.workout, length:100) %></td>
          <td><%= exercise.workout_date %></td>
          <td><%= link_to "Show", [current_user, exercise] %></td>
          <td><%= link_to "Edit", [:edit, current_user, exercise] %></td>
          <td><%= link_to "Delete", [current_user, exercise], method: :delete, data: { confirm: 'are you sure'} %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
    <div class="alert alert-info message-font text-center" role='alert'>
      No Workouts
    </div>
    <% end %>
    <div class="row">
      <div class="col-md-8 col-xs-12">

        <%= link_to "New Workout", new_user_exercise_path(current_user), class:'btn btn-primary'%>
      </div>

    </div>
    <%= content_tag :div, '', id:"chart", data: {workouts: @exercises} %>
  </div>




  <div class="col-md-5 col-xs-12">
    <div id='chat-window' class="col-md-12">
      <header class='text-center'>
        Channel: <%= current_room.name %>
      </header>

      <div class="col-md-2" id="followers">
        <% @followers.each do |follower| %>
        <%= link_to follower.user.full_name, user_exercises_path(current_user, roomId: follower.user.room.id), class:"followers" %>
        <br>
        <% end %>
      </div>

      <div class="col-md-10" id="messages-box">
        <div id='chat-box' data-channel='rooms' data-room-id=<%= current_room.id %>>
          <% @messages.each do |message|%>
          <%= render partial: 'shared/message', locals: {message: message}%>
          <% end %>
        </div>
        <div id="form-box">
          <%= form_for @message do |f| %>
          <%= f.text_field :body, id:"message-field", class:"form-control pull-left" %>
          <%= f.submit 'Post', class:"btn btn-default", id: "post-btn"%>
          <% end %>
        </div>
      </div>
    </div>
    <h2 class='text-center'><%= current_user.full_name%>'s Friends</h2>
    <% if current_user.friends.any?%>
    <% @friends.each do |friend| %>
    <div class="col-md-offset-3 col-md-6 friend_name">
      <%= link_to friend.full_name, friendship_path(current_user.current_friendship(friend)) %>
    </div>
    <div class="col-md-3">
      <div class="btn-unfollow">
        <%= link_to "Unfollow", friendship_path(current_user.current_friendship(friend)), method: :delete, data:{confirm:"Are you sure?"}, class: "btn btn-danger link" %>
      </div>

    </div>
    <% end%>

    <% else %>
    Search for others to add as friends.
    <% end%>
<% end %>


</div>

app/views/exercises/new.html.erb
<h2 class="text-center">Log New Workout for <%= current_user.full_name%></h2>
<%= render 'form'%>
<div class="col-md-6">
  <%= link_to 'Back', user_exercises_path(current_user), class: "btn btn-primary link", id:'new-exer-btn'%>
</div>

app/views/exercises/show.html.erb
<div class="col-xs-12 col-md-10 col-md-offset-1">
  <div class="">
    <h2 class="show-header">Showing <%= "#{@exercise.user.full_name}'s Workout Details"%></h2>
  </div>
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Duration:</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @exercise.duration%>
    </div>
  </div>
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Workout Details:</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= truncate(@exercise.workout, length:50)%>
    </div>
  </div>
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Workout Date:</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @exercise.workout_date %>
    </div>
  </div>
</div>
<div class="col-md-8 col-md-offset-2">
  <%= link_to 'Back', user_exercises_path(current_user), class: "btn btn-primary link", id:'back-btn'%>
</div>

app/views/friendships/show.html.erb
<h2><%= @friend.full_name %>'s Workouts (past 7 days)</h2>


<div class="col-md-8 col-xs-12">
  <% unless @exercises.empty? %>
  <table>
    <thead>
      <tr>
        <th>Duration (min)</th>
        <th>Workout Details</th>
        <th>Activity Date</th>
      </tr>
    </thead>
    <tbody>
      <% @exercises.each do |exercise| %>
        <tr>
          <td><%= exercise.duration %></td>
          <td><%= truncate(exercise.workout, length:100) %></td>
          <td><%= exercise.workout_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
    <div class="alert alert-info message-font text-center" role='alert'>
      No Workouts
    </div>
  <% end %>
  <%= content_tag :div, '', id:"chart", data: {workouts: @exercises} %>
  <div class="col-md-12">
    <%= link_to 'Back', user_exercises_path(current_user), class: "btn btn-primary link", id:'new-exer-btn'%>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workout-Log</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <div class="wrapper">
      <%= render "/shared/header"%>
      <div class="row content">
        <%= render "/shared/messages"%>
        <div class="<%= content_for?(:whole_page) ? 'container_fluid': 'container' %>">
          <%= yield %>
          <%= yield :whole_page %>
        </div>
      </div>
      <%= render "/shared/footer"%>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class='row' role='contentinfo'>
  <div class="container">
    <div class="col-md-12">
      <p><small>Copyright &copy; Talal Talhouk</small></p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Workout Log</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= form_tag(search_dashboards_path,
        class: "navbar-form navbar-left",
        role: "search") do %>
        <div class="form-group">
          <%= text_field_tag :search_name,
            nil,
            class:"form-control", placeholder:"Search by name" %>
        </div>
        <%= submit_tag "Search", class:"btn btn-default" %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",root_path %></li>
        <li><%= link_to "Atheletes Den",root_path %></li>
        <% if signed_in? %>
          <li>
            <%= link_to "My Lounge", user_exercises_path(current_user)%>
          </li>
          <li><%= link_to "Sign Out",destroy_user_session_path, method: :delete %></li>
          <li><p class="navbar-text">logged in as: <%= current_user.email%></p></li>
        <% end %>
        <% unless signed_in? %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_message.html.erb
<div class="message-row">
  <p class="message-body"><%= message.body %></p>
  <span>"<small><%= message.user.full_name %></small>"</span>
</div>

app/views/shared/_messages.html.erb
<div class="col-md-12">
  <% flash.each do |key, msg|%>
    <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> text-center">
      <strong><%= msg %></strong>
    </div>
  <% end %>

</div>